export const getGames = ({games}) => games.games;
export const getCurrentPage = ({games}) => games.currentPage;
export const getSearchText = ({games}) => games.searchText;
export const getGenresFilter = ({games}) => games.genresFilter;
export const getTagsFilter = ({games}) => games.tagsFilter;
export const getPlatformsFilter = ({games}) => games.platformsFilter;
export const getChekPage = ({games}) => games.chekPage;
export const getFetching = ({games}) => games.fetching;
export const getIsLoading = ({games}) => games.isLoading;
